### ISSUE TITLE
Website maintenance

### ISSUE THREAD

**Issue by rubiefawn** [rubiefawn/remedy#4]
## ⚠️ Todo
- [x] Add an `emoji` CSS class to clean up emoji in the `.md` files
- [x] Store emoji locally (custom emoji?)
- [x] Custom sidebar with [shields.io](https://shields.io/) badge links (github, discord) and other "presets" expansions (fantasy, scifi)

## ❓ Optional
- [ ] Pagination through the [docsify-pagination](https://github.com/imyelo/docsify-pagination) plugin
- [ ] Creative Commons link in footer
- [x] Change header & body fonts (something classic-ttrpg but readable)

## 🚑 Issues
- [x] ~~docsify will not display logo and title simultaneously~~ fixed via custom sidebar

**Comment by rubiefawn** [comment]
Suceeded by #7 & #8.
